# Build settings

port: 4000
markdown:  kramdown
# permalink: /:title
permalink: /:categories/:title
plugins:   [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Simon Pähler"
description: "Personal portolio"
author:      "Simon Pähler"

defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /articles/:title