#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Articles', url: 'articles'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
# - {name: 'The Azury Experience', url: 'azury-experience'}
# - {name: 'Stereoscopic Panorama Camera', url: 'stereo-camera'}
# - {name: 'Project One',   url: 'proj-1'}
# - {name: 'Project Two',   url: 'proj-2'}
# - {name: 'Project Three', url: 'proj-3'}
# - {name: 'Project Four',  url: 'proj-4'}
# - {name: 'Project Five',  url: 'proj-5'}

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://www.instagram.com/invadrsim'}
- {icon: 'github',    link: 'https://github.com/invdrsim'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/simon-p&auml;hler'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages'
  rel-author: 'Simon Pähler'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
