#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
# - {name: 'Articles', url: 'articles'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'The Azury Experience', url: 'azury-experience', thumbnail: 'thumbnail.jpg' }
- {name: 'Stereoscopic Panorama Camera', url: 'stereo-camera', thumbnail: 'thumbnail.jpg' }
- {name: 'The Floor is Lava', url: 'floor-is-lava', thumbnail: 'thumbnail.jpg' }
- {name: 'Motoliner VR', url: 'motoliner-vr', thumbnail: 'thumbnail.jpg' }
- {name: 'ijl', url: 'ijl', thumbnail: 'thumbnail.jpg' }
- {name: 'nogifsallowed.tumblr.com', url: 'nogifsallowed', thumbnail: 'hot_box.webp' }

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://www.instagram.com/invadrsim'}
- {icon: 'github',    link: 'https://github.com/invdrsim'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/simon-paehler'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages'
  rel-author: 'Simon Pähler'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''